import { useEffect, useMemo, useRef, useState } from 'react';
import { useSessionStore } from '../stores/sessionStore';
import { useFurnitureStore } from '../stores/furnitureStore';
import { useViolationStore } from '../stores/violationStore';
import { runClearanceAnalysis } from '../engine/clearance';
import { drawFloorPlan } from '../utils/floorPlan';
import { generateReport } from '../utils/pdfExport';
import { supabase } from '../supabase';
import { MULBERRY_PLACE_2BR } from '../data/roomData';
import type { RoomDimensions } from '../types';

const SUS_QUESTIONS = [
  'I think that I would like to use this system frequently.',
  'I found the system unnecessarily complex.',
  'I thought the system was easy to use.',
  'I think that I would need the support of a technical person to be able to use this system.',
  'I found the various functions in this system were well integrated.',
  'I thought there was too much inconsistency in this system.',
  'I would imagine that most people would learn to use this system very quickly.',
  'I found the system very cumbersome to use.',
  'I felt very confident using the system.',
  'I needed to learn a lot of things before I could get going with this system.',
];

const POST_SURVEY_QUESTIONS = [
  {
    key: 'q1',
    label:
      'After using Habi3D I understand which furniture violates clearance standards better',
  },
  {
    key: 'q2',
    label: 'After using Habi3D I feel more confident rearranging my furniture',
  },
  {
    key: 'q3',
    label: 'I was satisfied with the step-by-step recommendations',
  },
  {
    key: 'q4',
    label: 'The violation report generated by Habi3D was clear and useful',
  },
  {
    key: 'q5',
    label: 'Overall I am satisfied with Habi3D',
  },
] as const;

function getRoomDimensions(roomDimensions: RoomDimensions | null) {
  if (!roomDimensions) return { roomWidthCm: 360, roomLengthCm: 520 };
  return {
    roomWidthCm: Math.max(roomDimensions.livingWidthCm, roomDimensions.diningWidthCm),
    roomLengthCm: roomDimensions.livingDepthCm + roomDimensions.diningDepthCm,
  };
}

function computeSusScore(values: number[]) {
  const positive = [0, 2, 4, 6, 8].reduce((sum, index) => sum + (values[index] - 1), 0);
  const negative = [1, 3, 5, 7, 9].reduce((sum, index) => sum + (5 - values[index]), 0);
  return (positive + negative) * 2.5;
}

export default function EndSurveyScreen() {
  const navigateTo = useSessionStore((s) => s.navigateTo);
  const participantId = useSessionStore((s) => s.participantId);
  const participantCode = useSessionStore((s) => s.participantCode);
  const roomDimensions = useSessionStore((s) => s.roomDimensions);
  const items = useFurnitureStore((s) => s.items);

  const recommendations = useViolationStore((s) => s.recommendations);
  const spaceScoreBefore = useViolationStore((s) => s.spaceScoreBefore);
  const spaceScoreAfter = useViolationStore((s) => s.spaceScoreAfter);
  const setSpaceScoreAfter = useViolationStore((s) => s.setSpaceScoreAfter);

  const [susResponses, setSusResponses] = useState<number[]>(Array(10).fill(0));
  const [postResponses, setPostResponses] = useState({ q1: 0, q2: 0, q3: 0, q4: 0, q5: 0 });
  const [debrief, setDebrief] = useState({ q1: '', q2: '', q3: '', q4: '' });
  const [intendsToRearrange, setIntendsToRearrange] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [submitError, setSubmitError] = useState('');
  const [floorPlanDataUrl, setFloorPlanDataUrl] = useState('');
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const { roomWidthCm, roomLengthCm } = getRoomDimensions(roomDimensions);
  const result = useMemo(
    () => runClearanceAnalysis(items, roomWidthCm, roomLengthCm),
    [items, roomWidthCm, roomLengthCm],
  );

  const completedSteps = recommendations.filter((item) => item.resolved).length;
  const improvementPoints = Number((spaceScoreAfter - spaceScoreBefore).toFixed(1));

  useEffect(() => {
    if (spaceScoreAfter === 0) {
      setSpaceScoreAfter(result.spaceScoreBefore);
    }
  }, [result.spaceScoreBefore, setSpaceScoreAfter, spaceScoreAfter]);

  useEffect(() => {
    if (!canvasRef.current) return;
    drawFloorPlan(canvasRef.current, items, result.allClassifications, roomWidthCm, roomLengthCm);
    setFloorPlanDataUrl(canvasRef.current.toDataURL('image/png'));
  }, [items, result.allClassifications, roomWidthCm, roomLengthCm]);

  const susComplete = susResponses.every((value) => value >= 1 && value <= 5);
  const postComplete = Object.values(postResponses).every((value) => value >= 1 && value <= 5);
  const susScore = susComplete ? computeSusScore(susResponses) : 0;

  const handleSubmit = async () => {
    if (!participantId) {
      setSubmitError('Unable to submit without a participant ID.');
      return;
    }

    setSubmitting(true);
    setSubmitError('');

    try {
      const susPayload = SUS_QUESTIONS.reduce<Record<string, number>>((acc, _, index) => {
        acc[`q${index + 1}`] = susResponses[index];
        return acc;
      }, {});

      const { error: susError } = await supabase.from('sus_responses').insert({
        participant_id: participantId,
        ...susPayload,
        sus_score: susScore,
      });

      if (susError) throw susError;

      const { error: postError } = await supabase.from('post_survey_responses').insert({
        participant_id: participantId,
        spatial_awareness_improvement: postResponses.q1,
        confidence_improvement: postResponses.q2,
        recommendation_satisfaction: postResponses.q3,
        report_clarity: postResponses.q4,
        overall_satisfaction: postResponses.q5,
        intends_to_rearrange: intendsToRearrange,
        debrief_q1: debrief.q1,
        debrief_q2: debrief.q2,
        debrief_q3: debrief.q3,
        debrief_q4: debrief.q4,
      });

      if (postError) throw postError;

      const { error: updateError } = await supabase
        .from('space_utilization_scores')
        .update({
          score_after: spaceScoreAfter,
          improvement_points: improvementPoints,
        })
        .eq('participant_id', participantId);

      if (updateError) throw updateError;
      setSubmitted(true);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : String(error));
    } finally {
      setSubmitting(false);
    }
  };

  const handleDownload = () => {
    generateReport({
      participantCode: participantCode || 'unknown',
      building: MULBERRY_PLACE_2BR.building,
      unitType: MULBERRY_PLACE_2BR.unitType,
      date: new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      }),
      scoreBefore: spaceScoreBefore,
      scoreAfter: spaceScoreAfter,
      improvementPoints,
      violations: recommendations.map((item) => ({
        ruleCode: item.ruleCode,
        furnitureLabel: item.furnitureLabel,
        classification: item.classification,
        measuredCm: item.measuredCm,
        requiredCm: item.requiredCm,
        priorityScore: item.priorityScore,
      })),
      steps: recommendations.map((item, index) => ({
        stepNumber: index + 1,
        furnitureLabel: item.furnitureLabel,
        directionLabel: item.fixDirectionLabel,
        fixDirectionCm: item.fixDirectionCm,
      })),
      floorPlanDataUrl,
    });
  };

  return (
    <div className="screen">
      <div className="screen-header">
        <button className="back-btn" onClick={() => navigateTo('recommendation')} aria-label="Go back">
          &lt;
        </button>
        <div className="screen-header-info">
          <span className="step-label">Session evaluation</span>
          <h2>Final summary & survey</h2>
        </div>
      </div>

      <div className="card">
        <div className="card-header">
          <div className="card-icon card-icon-primary">✔</div>
          <div>
            <p className="card-title">Results summary</p>
            <p className="card-subtitle">Your last calculated Habi3D scores and recommendation progress</p>
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginTop: 16 }}>
          <div style={{ padding: 16, borderRadius: 16, background: '#F8FAFC' }}>
            <p className="info-label">Before</p>
            <p className="info-value">{spaceScoreBefore.toFixed(1)}%</p>
          </div>
          <div style={{ padding: 16, borderRadius: 16, background: '#ECFDF5' }}>
            <p className="info-label">After</p>
            <p className="info-value">{spaceScoreAfter.toFixed(1)}%</p>
          </div>
        </div>

        <div style={{ marginTop: 16 }}>
          <p className="info-label">Improvement</p>
          <p className="info-value" style={{ color: '#16A34A' }}>
            {improvementPoints >= 0 ? '+' : ''}
            {improvementPoints.toFixed(1)} points
          </p>
        </div>

        <div style={{ marginTop: 20, padding: 16, borderRadius: 16, background: '#EFF6FF' }}>
          <p className="info-label">Steps completed</p>
          <p className="info-value">{completedSteps} of {recommendations.length} violations resolved</p>
        </div>
      </div>

      <div className="card">
        <h3>Please rate Habi3D — System Usability Scale</h3>
        {SUS_QUESTIONS.map((question, index) => (
          <div key={question} style={{ marginTop: 18 }}>
            <p style={{ marginBottom: 8, fontWeight: 600 }}>{index + 1}. {question}</p>
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              {[1, 2, 3, 4, 5].map((value) => (
                <button
                  key={value}
                  type="button"
                  className={susResponses[index] === value ? 'btn btn-primary' : 'btn btn-secondary'}
                  style={{ minWidth: 42 }}
                  onClick={() => {
                    const next = [...susResponses];
                    next[index] = value;
                    setSusResponses(next);
                  }}
                >
                  {value}
                </button>
              ))}
            </div>
          </div>
        ))}
      </div>

      <div className="card">
        <h3>Post-survey</h3>
        {POST_SURVEY_QUESTIONS.map((question) => (
          <div key={question.key} style={{ marginTop: 18 }}>
            <p style={{ marginBottom: 8, fontWeight: 600 }}>{question.label}</p>
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              {[1, 2, 3, 4, 5].map((value) => (
                <button
                  key={value}
                  type="button"
                  className={postResponses[question.key] === value ? 'btn btn-primary' : 'btn btn-secondary'}
                  style={{ minWidth: 42 }}
                  onClick={() =>
                    setPostResponses((prev) => ({
                      ...prev,
                      [question.key]: value,
                    }))
                  }
                >
                  {value}
                </button>
              ))}
            </div>
          </div>
        ))}
      </div>

      <div className="card">
        <h3>Researcher: transcribe participant responses below</h3>
        <div style={{ marginTop: 18 }}>
          <label className="form-label" htmlFor="debrief-q1">
            Was there any step that confused you or was difficult to complete?
          </label>
          <textarea
            id="debrief-q1"
            className="form-input"
            rows={3}
            value={debrief.q1}
            onChange={(event) => setDebrief((prev) => ({ ...prev, q1: event.target.value }))}
          />
        </div>
        <div style={{ marginTop: 18 }}>
          <label className="form-label" htmlFor="debrief-q2">
            Which was more useful — the AR guide or the final report?
          </label>
          <textarea
            id="debrief-q2"
            className="form-input"
            rows={3}
            value={debrief.q2}
            onChange={(event) => setDebrief((prev) => ({ ...prev, q2: event.target.value }))}
          />
        </div>
        <div style={{ marginTop: 18 }}>
          <label className="form-label" htmlFor="debrief-q3">
            Do you plan to physically rearrange your furniture based on today's session?
          </label>
          <textarea
            id="debrief-q3"
            className="form-input"
            rows={3}
            value={debrief.q3}
            onChange={(event) => setDebrief((prev) => ({ ...prev, q3: event.target.value }))}
          />
          <div style={{ marginTop: 12, display: 'flex', gap: 12 }}>
            <button
              type="button"
              className={intendsToRearrange ? 'btn btn-primary' : 'btn btn-secondary'}
              onClick={() => setIntendsToRearrange(true)}
            >
              Yes
            </button>
            <button
              type="button"
              className={!intendsToRearrange ? 'btn btn-primary' : 'btn btn-secondary'}
              onClick={() => setIntendsToRearrange(false)}
            >
              No
            </button>
          </div>
        </div>
        <div style={{ marginTop: 18 }}>
          <label className="form-label" htmlFor="debrief-q4">
            Is there anything you would want the app to do that it currently does not?
          </label>
          <textarea
            id="debrief-q4"
            className="form-input"
            rows={3}
            value={debrief.q4}
            onChange={(event) => setDebrief((prev) => ({ ...prev, q4: event.target.value }))}
          />
        </div>
      </div>

      {submitError && (
        <div className="card" style={{ borderLeft: '4px solid #E02424', background: '#FEE2E2' }}>
          <p style={{ margin: 0, color: '#991B1B' }}>{submitError}</p>
        </div>
      )}

      {submitted && (
        <div className="card" style={{ borderLeft: '4px solid #16A34A', background: '#D1FAE5' }}>
          <p style={{ margin: 0, color: '#064E3B', fontWeight: 700 }}>
            Session complete — thank you
          </p>
        </div>
      )}

      <button
        className="btn btn-primary"
        type="button"
        onClick={handleSubmit}
        disabled={!susComplete || !postComplete || submitting || submitted}
      >
        {submitting ? 'Submitting evaluation…' : 'Submit evaluation'}
      </button>

      {submitted && (
        <button
          className="btn btn-secondary"
          type="button"
          onClick={handleDownload}
          style={{ marginTop: 12 }}
        >
          Download PDF Report
        </button>
      )}

      <canvas ref={canvasRef} style={{ display: 'none' }} width={720} height={520} />
    </div>
  );
}
